### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by arsaboo** [TheSwert/opencv_darknet#1]
I am getting the following error continuously:
```
Mon Oct 22 2018 14:38:29 GMT-0400 (Eastern Daylight Time)

Update for image_processing.opencv_porch fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/image_processing/__init__.py", line 134, in async_update
    await self.async_process_image(image.content)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/image_processing/opencv_darknet.py", line 152, in process_image
    net = cv2.dnn.readNetFromDarknet(self.modelConfiguration, self.modelWeights) # pylint:disable=E1101
cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:507: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'
```

**Comment by TheSwert** [comment]
I have a feeling you may have downloaded the cfg file wrong from the site (done it myself before). If you're doing a wget, you need to pull from the raw github location. Assuming you're using YOLOv3-tiny you would use the below link.

https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg

**Comment by arsaboo** [comment]
Looks like that helped. Just to make sure I am doing this right, here's my config:
```
  - platform: opencv_darknet
    name: Porch Object Detection
    source:
      - entity_id: camera.porch
    options:
      detect_model: /home/homeassistant/.homeassistant/deps/yolov3-tiny.cfg
      weights: /home/homeassistant/.homeassistant/deps/yolov3-tiny.weights
      labels: /home/homeassistant/.homeassistant/deps/coco.names
      confidence: 0.55
```
and I get a new entity `image_processing.opencv_porch`. 
![image](https://user-images.githubusercontent.com/18319734/47371835-7fb8a780-d6b6-11e8-883c-8d0ff5eb4f4b.png)

There is no way to see the output (other than the value of the entity). Also, I am assuming that we have to manually run the `image_processing.scan` service for the detection.

**Comment by TheSwert** [comment]
Your config looks fine. You should see a component on your overview page unless you're doing some fancy customization of it. You are correct that you will not see any kind of image with bounding boxes on it. The image processor will automatically run at the scan interval (every 30 seconds by default). You can shorten the interval by updating the variable SCAN_INTERVAL.

**Comment by arsaboo** [comment]
Got it...everything is working fine. You should submit this to the HA repo :+1:
